services:
  zenn:
    build:
        context: ./
        dockerfile: zenn.dockerfile
    image: zenn:latest
    container_name: zenn
    working_dir: /work
    volumes:
      - ./:/work
    ports:
      - "8000:8000"
